version: "3.9"

services:
  database:
    image: postgres
    container_name: database_ngcash
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_cash
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database_ngcash:5432/db_cash
    container_name: dbapp
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
      
